conf/urls.py
#-*- coding:utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from account.views import LogoutView, SigninFormView, ActivationView, IsActiveView, RePasswordFormView
from gigdate.views import Index, DateListView, LastListView
from seo.views import YandexMailVerifed, Robotstxt
from contents.views import LandingPage, LandingPage2

urlpatterns = [

    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<type_date>\w+)/$', Index.as_view(), name='home_month'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', Index.as_view(), name='home_month_dates'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<type_date>\w+)/$', DateListView.as_view(), name='date_day'),
    url(r'^last/$', LastListView.as_view(), name='last_all'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^user/', include('account.pub_urls', namespace='users')),
    url(r'^d/', include('gigdate.urls', namespace='gigdate')),
    url(r'^moder/', include('moderator.urls', namespace='moderator')),
    url(r'^info/', include('contents.urls', namespace='contents')),
    url(r'^crm/', include('crm.urls', namespace='crm')),

    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^signin/$', SigninFormView.as_view(), name='signin'),
    url(r'^is_active/$', IsActiveView.as_view(), name='is_active'),
    url(r'^is_active/resend/$', IsActiveView.as_view(), {'resend': 're_activate'}, name='re_is_active'),
    url(r'^user_activation/', ActivationView.as_view(), name='activation'),
    url(r'^repassword/', RePasswordFormView.as_view(), name='repassword'),
    url(r'^start/', LandingPage.as_view(), name='landingpage'),
    url(r'^start2/', LandingPage2.as_view(), name='landingpage2'),

    url(r'^cf6a2b36ecd97bf07de3f80906e7f2e9ab6cc852917cf7e7bd639612b615520c.html$', YandexMailVerifed.as_view()),
    url(r'^robots.txt', Robotstxt.as_view()),

    url(r'^$', Index.as_view(), name='home'),

    url(r'^(?P<type_date>\w+)/$', Index.as_view(), name='home_two'),
]


# Инициализируем папку media
if settings.DEBUG:
    if settings.MEDIA_ROOT:
        from django.conf.urls.static import static
        from django.contrib.staticfiles.urls import staticfiles_urlpatterns
        urlpatterns += static(settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)
    # Эта строка опциональна и будет добавлять url'ы только при DEBUG = True
    urlpatterns += staticfiles_urlpatterns()

crm/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.decorators import user_passes_test
from crm.views import HomeCRM, TicketListView, TicketDetailView, ChartUserStaticJS, UsersVenuesListView,\
    UsersVenuesDetailView


urlpatterns = [
    url(r'^$', user_passes_test(lambda u: u.is_superuser or u.is_moderator)(HomeCRM.as_view()), name='home'),
    url(r'^tickets/$', user_passes_test(lambda u: u.is_superuser or u.is_moderator)(TicketListView.as_view()),
        name='tickets'),
    url(r'^ticket/(?P<pk>\d+)/$',
        user_passes_test(lambda u: u.is_superuser or u.is_moderator)(TicketDetailView.as_view()), name='ticket_views'),
    url(r'^chart/user_static.js$', user_passes_test(lambda u: u.is_superuser or u.is_moderator)(ChartUserStaticJS.as_view()),
        name='chart_user_static'),

    url(r'^users/venues/$', user_passes_test(lambda u: u.is_superuser or u.is_moderator)(UsersVenuesListView.as_view()),
        name='users_venues'),
    url(r'^users/venues/(?P<pk>\d+)/$', user_passes_test(lambda u: u.is_superuser or u.is_moderator)(UsersVenuesDetailView.as_view()),
        name='users_venues_view'),
]

crm/models.py
# -*- coding:utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse

from account.models import User


class Ticket(models.Model):
    """ Tickets """
    create = models.DateTimeField(_(u'Create'), auto_now_add=True, blank=True, null=True)
    read = models.BooleanField(_(u"Read"), default=True, blank=True)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='ticket_children')
    page = models.CharField(_(u'Page url'), max_length=250, null=True, blank=True)

    user = models.ForeignKey(User, verbose_name=_(u'User'), null=True, blank=True)
    email = models.EmailField(_(u'email'), null=True, blank=True)
    subject = models.CharField(_(u'Subject'), max_length=100, null=True, blank=False)
    text = models.TextField(_(u'Text'), null=True, blank=False)

    SPCT0, SPCT1, SPCT2, SPCT3, SPCT4, SPCT5 = range(0, 6)
    SPCTS = (
        (SPCT0, _(u'Advertising / Partnerships / Sponsorships')),
        (SPCT1, _(u'Deals')),
        (SPCT2, _(u'Registration & Profiles')),
        (SPCT3, _(u'Requests')),
        (SPCT4, _(u'Vacancies')),
        (SPCT5, _(u'Other')),
    )
    category = models.IntegerField(verbose_name=_(u'Support category'), choices=SPCTS, blank=False)

    def __unicode__(self):
        return u"%s" % self.subject

    def get_absolute_url(self):
        return reverse('crm:ticket_views', args=[self.pk])

    class Meta:
        verbose_name = _(u'Tickets')
        verbose_name_plural = _(u'Tickets')
        ordering = ('-create',)

crm/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.utils.translation import ugettext_lazy as _
from crm.models import Ticket


class TicketForm(forms.ModelForm):
    """
    Форма Отправки текета
    """

    def __init__(self, *args, **kwargs):
        super(TicketForm, self).__init__(*args, **kwargs)
        self.fields['category'].widget.attrs['class'] = 'nostyle'

    class Meta:
        model = Ticket
        fields = ('user', 'email', 'subject', 'text', 'category', 'page')


class ReTicketForm(forms.ModelForm):
    """
    Форма Отправки текета
    """
    class Meta:
        model = Ticket
        fields = ('user', 'text')

crm/views.py
# -*- coding:utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django.views.generic.base import RedirectView, TemplateView
from django.views.generic import DetailView, ListView, View
from django.views.generic.edit import FormView, UpdateView
from django.core.urlresolvers import reverse
from django.conf import settings
from django.db.models import Q
from django.core.mail import send_mail
from account.models import User, AgentProfile, ArtistProfile, ClubProfile
from gigdate.models import DateAll
from trade.models import Trades
from crm.models import Ticket
from crm.forms import ReTicketForm


class HomeCRM(TemplateView):
    """ Main CRM """
    template_name = 'crm/home.html'

    def get_context_data(self, **kwargs):
        kwargs['count_user'] = User.objects.all().count()
        kwargs['count_dates'] = DateAll.objects.all().count()
        kwargs['count_request'] = Trades.objects.all().count()
        kwargs['count_deals'] = Trades.objects.filter(status_trade=Trades.STRADE2).count()
        return kwargs


class TicketListView(ListView):
    """ Tikets """
    template_name = 'crm/tickets/ticket_list.html'
    model = Ticket
    paginate_by = 40

    def get_context_data(self, **kwargs):
        context = super(TicketListView, self).get_context_data(**kwargs)
        context['ticket_site'] = True
        return context

    def get_queryset(self):
        return self.model.objects.filter(parent__isnull=True)


class TicketDetailView(FormView, DetailView):
    model = Ticket
    template_name = 'crm/tickets/ticket_view.html'
    form_class = ReTicketForm

    def get_success_url(self):
        return reverse('crm:ticket_views', kwargs={'pk': self.object.pk})

    # def get(self, request, *args, **kwargs):
    #     self.object = self.get_object()
    #     if self.object.read:
    #         self.object.read = False
    #         self.object.save()
    #     return super(TicketDetailView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(TicketDetailView, self).get_context_data(**kwargs)
        context['form'] = self.get_form()
        context['ticket_site'] = True
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        # Here, we would record the user's interest using the message
        # passed in form.cleaned_data['message']
        f = form.save(commit=False)
        self.object = self.get_object()
        f.parent = self.object
        f.subject = u"%s %s" % (_(u"Re:"), self.object.subject)
        f.category = self.object.category
        f.user = self.request.user
        f.save()

        message = u">%s: %s \n\r>%s: %s \n\r>%s: %s\n\r\n\r-------\n\r%s: %s" % (_(u"Subject"), f.parent.subject,
                                                    _(u"Related Issue"), f.parent.get_category_display(),
                                                    _(u"Message"), f.parent.text,
                                                    _(u"The answer"), f.text)
        subject = u"%s #%s" % (_('Ticket'), f.pk)
        to_email = f.user.email if f.user else f.email
        from_email = settings.EMAIL_TICKETS
        send_mail(subject, message, from_email, [to_email])

        return super(TicketDetailView, self).form_valid(form)


class ChartUserStaticJS(TemplateView):
    #  https://google-developers.appspot.com/chart/interactive/docs/gallery/linechart
    content_type = 'text/plain; charset=utf-8'
    template_name = 'crm/chart/user_static.html'

    def get_users_statistics(self):
        users = User.objects.all().only('date_joined', 'is_active')
        # print users.query

    def get_context_data(self, **kwargs):
        context = super(ChartUserStaticJS, self).get_context_data(**kwargs)
        # context['content'] = robots[0] if robots else None
        self.get_users_statistics()
        return context


class UsersVenuesListView(ListView):
    """ Tikets """
    template_name = 'crm/users/venues_list.html'
    model = ClubProfile
    paginate_by = 40
    ordering = '-create'

    def get_context_data(self, **kwargs):
        context = super(UsersVenuesListView, self).get_context_data(**kwargs)
        context['users_venues'] = True
        return context


class UsersVenuesDetailView(DetailView):
    template_name = 'crm/users/venues_detail.html'
    model = ClubProfile

    def get_context_data(self, **kwargs):
        context = super(UsersVenuesDetailView, self).get_context_data(**kwargs)
        context['users_venues'] = True
        context['trades_inbox'] = Trades.objects.filter(club_date=context['object'])
        context['trades_outbox'] = Trades.objects.filter(club_trade=context['object'])
        context['trades_deals'] = Trades.objects.filter(Q(club_date=context['object']) | Q(club_trade=context['object']), Q(status_trade=Trades.STRADE2))
        context['trades_rejected'] = Trades.objects.filter(Q(club_date=context['object']) | Q(club_trade=context['object']), Q(status_trade=Trades.STRADE4))
        return context

templates/crm/users/venues_list.html
{% extends 'crm/base.html' %}{% load staticfiles i18n %}
{% block block_css %}
    <link href="{% static 'metronic/assets/admin/pages/css/inbox.css' %}" rel="stylesheet" type="text/css"/>
{% endblock %}
{% block body_class %}page-header-fixed page-quick-sidebar-over-content{% endblock %}

{% block content %}
<!-- BEGIN PAGE HEADER-->
<h3 class="page-title">
Users <small>venues</small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="{% url 'crm:home' %}">{% trans 'Home' %}</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            {% trans 'Users' %}
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="{% url 'crm:users_venues' %}">{% trans 'Venues' %}</a>
        </li>
    </ul>
</div>
<!-- END PAGE HEADER-->
<div class="row inbox">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box blue-hoki">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-globe"></i>Venues list
                </div>
                <div class="tools">
{#                    <th class="pagination-control" colspan="3">#}
                        {% if page_obj.paginator.num_pages %}
                            {% if page_obj.has_previous %}
                                <a style="height: auto" href="{% url 'crm:users_venues' %}{% if page_obj.previous_page_number > 1 %}?page={{ page_obj.previous_page_number }}{% endif %}" class="btn btn-sm blue"><i class="fa fa-angle-left"></i></a>
                            {% endif %}

                            <span class="pagination-info">
                                {% trans 'Page:' %} {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                            </span>

                            {% if page_obj.has_next %}
                                <a style="height: auto" href="{% url 'crm:users_venues' %}?page={{ page_obj.next_page_number }}" class="btn btn-sm blue"><i class="fa fa-angle-right"></i></a>
                            {% endif %}
                        {% endif %}
{#                    </th>#}
                </div>
            </div>
            <div class="portlet-body">
                <table class="table table-striped table-bordered table-hover" id="sample_1">
                <thead>
                <tr>
                    <th>{% trans 'Create' %}</th>
                    <th>{% trans 'Name' %}</th>
                    <th>{% trans 'User Name' %}</th>
                    <th>{% trans 'User Email' %}</th>
                    <th>{% trans 'Base/Agent' %}</th>
                    <th>{% trans 'Dates' %}</th>
                    <th>{% trans 'Requests' %}</th>
                    <th>{% trans 'Deals' %}</th>
                </tr>
                </thead>
                <tbody>
                {% for venue in object_list %}<tr>
                    <td>
                        {% now "SHORT_DATE_FORMAT" as now_today %}
                        {% if venue.create|date:"SHORT_DATE_FORMAT" == now_today %}{{ venue.create|date:"TIME_FORMAT" }}
                        {% else %}{{ venue.create|date:"DATE_FORMAT" }}{% endif %}
                    </td>
                    <td><a href="{% url 'crm:users_venues_view' venue.pk %}" class="edit">{{ venue.nickname }}</a></td>
                    <td>{{ venue.user.get_full_name }}</td>
                    <td>{{ venue.user.email }}</td>
                    <td>{% if venue.agent %}{{ venue.agent.nickname }}{% else %}{% trans '-' %}{% endif %}</td>
                    <td>{{ venue.dates_count }}</td>
                    <td>{{ venue.trade_count }}</td>
                    <td>{{ venue.deals_count }}</td>
                </tr>{% endfor %}
                </tbody>
                </table>
            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>

{% endblock %}