account/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, user_passes_test
from account.views import MainView, AjaxCity, AgentFormView, ArtistFormView, ClubFormView, AgentArtistListView,\
    AgentClubListView, AgentArtistCreateView, AgentClubCreateView, AgentClubUpdateView, AgentArtistUpdateView,\
    AjaxArtist, AjaxClub, MailboxAjax, MailBoxListView, MailBoxOutListView, MailboxDetailView, SendMail
from gigdate.views import GigdateallListView, GigdateallFilterListView, GigdateUpdateView, GigBarterUpdateView,\
    GigTenderUpdateView
from trade.views import TradeListView, tradedetai, DealsDetailView, DealsDetailViewPrint, DealsDetailViewPDF
from gigcoin.views import TransactionCoinList, PromoCodeFormView, PaidView


urlpatterns = [
    url(r'^agent/$', login_required(AgentFormView.as_view()), name='agent'),
    url(r'^artist/$', login_required(ArtistFormView.as_view()), name='artist'),
    url(r'^venue/$', login_required(ClubFormView.as_view()), name='club'),
    url(r'^agent/artist/$', login_required(AgentArtistListView.as_view()), name='agent_artist'),
    url(r'^agent/venue/$', login_required(AgentClubListView.as_view()), name='agent_club'),
    url(r'^agent/artist/add/$', login_required(AgentArtistCreateView.as_view()), name='agent_artist_add'),
    url(r'^agent/venue/add/$', login_required(AgentClubCreateView.as_view()), name='agent_club_add'),
    url(r'^agent/artist/edit/(?P<slug>[^/]+)/$', login_required(AgentArtistUpdateView.as_view()), name='agent_artist_edit'),
    url(r'^agent/venue/edit/(?P<slug>[^/]+)/$', login_required(AgentClubUpdateView.as_view()), name='agent_club_edit'),

    url(r'^dates/$', login_required(GigdateallListView.as_view()), name='dates'),
    url(r'^dates/(?P<pk>\d+)/(?P<slug>\w+)/$', login_required(GigdateallFilterListView.as_view()), name='dates_filter'),
    url(r'^dates/edit_(?P<slug>[^/]+)/date/$', login_required(GigdateUpdateView.as_view()), name='edit_gigdate'),
    url(r'^dates/edit_(?P<slug>[^/]+)/barter/$', login_required(GigBarterUpdateView.as_view()), name='edit_barter'),
    url(r'^dates/edit_(?P<slug>[^/]+)/tender/$', login_required(GigTenderUpdateView.as_view()), name='edit_tender'),

    url(r'^ajax_city/(?P<id>[0-9]+)/$', AjaxCity.as_view(), name='ajax_city'),
    url(r'^get_artist/(?P<id>[0-9]+)/$', AjaxArtist.as_view(), name='ajax_artist'),
    url(r'^get_club/(?P<id>[0-9]+)/$', AjaxClub.as_view(), name='ajax_club'),

    url(r'^mailbox_ajax/$', MailboxAjax.as_view(), name='mailbox_ajax'),
    url(r'^message/$', MailBoxListView.as_view(), name='mailbox'),
    url(r'^message/out/$', MailBoxOutListView.as_view(), name='mailbox_out'),
    url(r'^message/(?P<pk>\d+)/$', MailboxDetailView.as_view(), name='mailbox_view'),

    url(r'^trade/$', TradeListView.as_view(), name='trade_list'),
    url(r'^trade/(?P<pk>\d+)/$', tradedetai, name='trade_view'),
    url(r'^trade/(?P<pk>\d+)/deals/$', DealsDetailView.as_view(), name='deals_view'),
    url(r'^trade/(?P<pk>\d+)/deals/print/$', DealsDetailViewPrint.as_view(), name='deals_print'),
    url(r'^trade/(?P<pk>\d+)/deals/pdf/$', DealsDetailViewPDF.as_view(), name='deals_pdf'),

    url(r'^send_mail/$', user_passes_test(lambda u: u.is_superuser or u.is_moderator)(SendMail.as_view()), name='send_mail'),

    url(r'^billing/$', TransactionCoinList.as_view(), name='billing'),
    url(r'^promo_code/$', PromoCodeFormView.as_view(), name='promo_code'),
    url(r'^paid_coin/$', PaidView.as_view(), name='paid_coin'),

    url(r'^$', login_required(MainView.as_view()), name='main'),
]

conf/urls.py
#-*- coding:utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from account.views import LogoutView, SigninFormView, ActivationView, IsActiveView, RePasswordFormView
from gigdate.views import Index, DateListView, LastListView
from seo.views import YandexMailVerifed, Robotstxt
from contents.views import LandingPage, LandingPage2

urlpatterns = [

    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<type_date>\w+)/$', Index.as_view(), name='home_month'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', Index.as_view(), name='home_month_dates'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<type_date>\w+)/$', DateListView.as_view(), name='date_day'),
    url(r'^last/$', LastListView.as_view(), name='last_all'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^user/', include('account.pub_urls', namespace='users')),
    url(r'^d/', include('gigdate.urls', namespace='gigdate')),
    url(r'^moder/', include('moderator.urls', namespace='moderator')),
    url(r'^info/', include('contents.urls', namespace='contents')),
    url(r'^crm/', include('crm.urls', namespace='crm')),

    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^signin/$', SigninFormView.as_view(), name='signin'),
    url(r'^is_active/$', IsActiveView.as_view(), name='is_active'),
    url(r'^is_active/resend/$', IsActiveView.as_view(), {'resend': 're_activate'}, name='re_is_active'),
    url(r'^user_activation/', ActivationView.as_view(), name='activation'),
    url(r'^repassword/', RePasswordFormView.as_view(), name='repassword'),
    url(r'^start/', LandingPage.as_view(), name='landingpage'),
    url(r'^start2/', LandingPage2.as_view(), name='landingpage2'),

    url(r'^cf6a2b36ecd97bf07de3f80906e7f2e9ab6cc852917cf7e7bd639612b615520c.html$', YandexMailVerifed.as_view()),
    url(r'^robots.txt', Robotstxt.as_view()),

    url(r'^$', Index.as_view(), name='home'),

    url(r'^(?P<type_date>\w+)/$', Index.as_view(), name='home_two'),
]


# Инициализируем папку media
if settings.DEBUG:
    if settings.MEDIA_ROOT:
        from django.conf.urls.static import static
        from django.contrib.staticfiles.urls import staticfiles_urlpatterns
        urlpatterns += static(settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)
    # Эта строка опциональна и будет добавлять url'ы только при DEBUG = True
    urlpatterns += staticfiles_urlpatterns()

crm/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.decorators import user_passes_test
from crm.views import HomeCRM, TicketListView, TicketDetailView, ChartUserStaticJS, UsersVenuesListView,\
    UsersVenuesDetailView


urlpatterns = [
    url(r'^$', user_passes_test(lambda u: u.is_superuser or u.is_moderator)(HomeCRM.as_view()), name='home'),
    url(r'^tickets/$', user_passes_test(lambda u: u.is_superuser or u.is_moderator)(TicketListView.as_view()),
        name='tickets'),
    url(r'^ticket/(?P<pk>\d+)/$',
        user_passes_test(lambda u: u.is_superuser or u.is_moderator)(TicketDetailView.as_view()), name='ticket_views'),
    url(r'^chart/user_static.js$', user_passes_test(lambda u: u.is_superuser or u.is_moderator)(ChartUserStaticJS.as_view()),
        name='chart_user_static'),

    url(r'^users/venues/$', user_passes_test(lambda u: u.is_superuser or u.is_moderator)(UsersVenuesListView.as_view()),
        name='users_venues'),
    url(r'^users/venues/(?P<pk>\d+)/$', user_passes_test(lambda u: u.is_superuser or u.is_moderator)(UsersVenuesDetailView.as_view()),
        name='users_venues_view'),
]

gigdate/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from gigdate.views import AddGigdateCreateView, AddGigTenderCreateView, AddGigBarterCreateView,\
    GigdateDetailView, GigbarterDetailView, GigtenderDetailView, FilterDayFormView, GoDateRedirect, GoTenderRedirect,\
    GigdateRedirect, GigTenderRedirect, GigBarterRedirect

urlpatterns = [
    url(r'^add_gigdate/$', login_required(AddGigdateCreateView.as_view()), name='add_gigdate'),
    url(r'^add_barter/$', login_required(AddGigBarterCreateView.as_view()), name='add_barter'),
    url(r'^add_tender/$', login_required(AddGigTenderCreateView.as_view()), name='add_tender'),


    url(r'^(?P<pk>\d+)/gigdate/$', GigdateRedirect.as_view(), name='gigdate_302'),
    url(r'^(?P<pk>\d+)/barter/$', GigBarterRedirect.as_view(), name='barter_302'),
    url(r'^(?P<pk>\d+)/tender/$', GigTenderRedirect.as_view(), name='tender_302'),

    url(r'^(?P<slug>[^/]+)/gigdate/$', GigdateDetailView.as_view(), name='gigdate_view'),
    url(r'^(?P<slug>[^/]+)/barter/$', GigbarterDetailView.as_view(), name='barter_view'),
    url(r'^(?P<slug>[^/]+)/tender/$', GigtenderDetailView.as_view(), name='tender_view'),

    url(r'^go/gigdate/(?P<artist>\d+)/(?P<year>\d{4})-(?P<month>\d{1,2})-(?P<day>\d{1,2})/$', GoDateRedirect.as_view(), name='go_gigdate'),
    url(r'^go/tender/(?P<venue>\d+)/(?P<year>\d{4})-(?P<month>\d{1,2})-(?P<day>\d{1,2})/$', GoTenderRedirect.as_view(), name='go_tender'),

    url(r'^filter_day/$', FilterDayFormView.as_view(), name='filter_day'),
]

templates/gigdate/account/dates_list.html
{% extends 'gigdate/account/main.html' %}
{% load static i18n user_tag %}

{% block profile_content %}
<div class="content-profile">
    <h2>{% trans 'My dates' %} ({{ page_obj.paginator.count }})</h2>
    {% if gigdates %}
    <table class="table_gigdates">
        <tr id="th">
            <th width="120">{% trans 'Event date' %}</th>
            <th>{% trans 'Profile' %}</th>
            <th width="150">{% trans 'Date type' %}</th>
            <th width="150">{% trans 'Created' %}</th>
        </tr>
        {% for gigdate in gigdates %}
        <tr>
            <td><a href="{{ gigdate.get_absolute_url }}">{{ gigdate.dates|date:"SHORT_DATE_FORMAT" }}</a>{% if gigdate.gigdate.second_country or gigdate.gigbarter.second_country %} <img title="{% trans 'This is a second date' %}" src="{% static 'images/ui_2Date.png' %}" />{% endif %}</td>
            <td>{{ gigdate.username_child|slice:":30" }}{% if gigdate.username_child|letterscount > 30 %}<i class="last_letter">{{ gigdate.username_child|slice:"30:31" }}...</i>{% endif %}</td>
            <td>{{ gigdate.get_type_date_display }}</td>
            <td>{{ gigdate.create|date:"SHORT_DATETIME_FORMAT" }}</td>
        </tr>
        {% endfor %}
    </table>
    {% if is_paginated %}<div class="pagination pagination-centered">
        <ul>
            {% if page_obj.has_previous %}<li {% if not page_obj.has_previous %}class="disabled"{% endif %}><a href="{% if page_obj.previous_page_number == 1 %}./{% else %}?page={{ page_obj.previous_page_number }}{% endif %}"><</a></li>{% endif %}

            {% for p in page_obj.paginator.page_range %}
                <li {% ifequal p page_obj.number %}class="active"{% endifequal %}><a href="{% if p == 1 %}./{% else %}?page={{ p }}{% endif %}">{{ p }}</a></li>
            {% endfor %}

            {% if page_obj.has_next %}<li {% if not page_obj.has_next %}class="disabled"{% endif %}><a href="?page={{ page_obj.next_page_number }}">></a></li>{% endif %}
        </ul>
    </div>{% endif %}
    {% else %}
        <center>{% trans 'Dates not found' %}</center>
    {% endif %}

</div>
{% endblock %}

templates/gigdate/account/main.html
{% extends 'account/main.html' %}
{% load static i18n user_tag %}
{% block extended_css %}<link rel="stylesheet" href="{% static 'css/gigdates.css' %}" type="text/css" />{% endblock %}
{% block extended_js %}<script type="text/javascript" src="{% static 'js/gigdates.js' %}"></script>{% endblock %}

{% block account_content %}
<div class="tab-wrapper">
    <div class="tab active-tab">
        <div class="profile-form alt-input-form">
            <ul class="side-profile-nav">
            {% if artists %}
            <fieldset>
            <legend>{% trans 'Artists' %}</legend>
                {% for artist in artists %}
            <li><a{% if art_id == artist.pk %} class="active"{% endif %} href="{% url 'account:dates_filter' artist.pk 'artist' %}"><b>{{ forloop.counter }}.</b> {{ artist.nickname|slice:":10" }}{% if artist.nickname|letterscount > 10 %}<i class="last_letter">{{ artist.nickname|slice:"10:11" }}...</i>{% endif %} ({{ artist.dates_count }})</a></li>
                {% endfor %}
            </fieldset>
            {% else %}
            <li><a href="{% url 'account:artist' %}">{% trans 'Create an artist' %}</a></li>
            {% endif %}

            {% if clubs %}
            <fieldset>
            <legend>{% trans 'Venues' %}</legend>
                {% for club in clubs %}
            <li><a{% if clb_id == club.pk %} class="active"{% endif %} href="{% url 'account:dates_filter' club.pk 'venue' %}"><b>{{ forloop.counter }}.</b> {{ club.nickname|slice:":10" }}{% if club.nickname|letterscount > 10 %}<i class="last_letter">{{ club.nickname|slice:"10:11" }}...</i>{% endif %} ({{ club.dates_count }})</a></li>
                {% endfor %}
            </fieldset>
            {% else %}
            <li><a href="{% url 'account:club' %}">{% trans 'Create a venue' %}</a></li>
            {% endif %}

            </ul>
            {% block profile_content %}

            {% endblock %}

        </div>
    </div>
</div>
{% endblock %}