account/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, user_passes_test
from account.views import MainView, AjaxCity, AgentFormView, ArtistFormView, ClubFormView, AgentArtistListView,\
    AgentClubListView, AgentArtistCreateView, AgentClubCreateView, AgentClubUpdateView, AgentArtistUpdateView,\
    AjaxArtist, AjaxClub, MailboxAjax, MailBoxListView, MailBoxOutListView, MailboxDetailView, SendMail
from gigdate.views import GigdateallListView, GigdateallFilterListView, GigdateUpdateView, GigBarterUpdateView,\
    GigTenderUpdateView
from trade.views import TradeListView, tradedetai, DealsDetailView, DealsDetailViewPrint, DealsDetailViewPDF
from gigcoin.views import TransactionCoinList, PromoCodeFormView, PaidView


urlpatterns = [
    url(r'^agent/$', login_required(AgentFormView.as_view()), name='agent'),
    url(r'^artist/$', login_required(ArtistFormView.as_view()), name='artist'),
    url(r'^venue/$', login_required(ClubFormView.as_view()), name='club'),
    url(r'^agent/artist/$', login_required(AgentArtistListView.as_view()), name='agent_artist'),
    url(r'^agent/venue/$', login_required(AgentClubListView.as_view()), name='agent_club'),
    url(r'^agent/artist/add/$', login_required(AgentArtistCreateView.as_view()), name='agent_artist_add'),
    url(r'^agent/venue/add/$', login_required(AgentClubCreateView.as_view()), name='agent_club_add'),
    url(r'^agent/artist/edit/(?P<slug>[^/]+)/$', login_required(AgentArtistUpdateView.as_view()), name='agent_artist_edit'),
    url(r'^agent/venue/edit/(?P<slug>[^/]+)/$', login_required(AgentClubUpdateView.as_view()), name='agent_club_edit'),

    url(r'^dates/$', login_required(GigdateallListView.as_view()), name='dates'),
    url(r'^dates/(?P<pk>\d+)/(?P<slug>\w+)/$', login_required(GigdateallFilterListView.as_view()), name='dates_filter'),
    url(r'^dates/edit_(?P<slug>[^/]+)/date/$', login_required(GigdateUpdateView.as_view()), name='edit_gigdate'),
    url(r'^dates/edit_(?P<slug>[^/]+)/barter/$', login_required(GigBarterUpdateView.as_view()), name='edit_barter'),
    url(r'^dates/edit_(?P<slug>[^/]+)/tender/$', login_required(GigTenderUpdateView.as_view()), name='edit_tender'),

    url(r'^ajax_city/(?P<id>[0-9]+)/$', AjaxCity.as_view(), name='ajax_city'),
    url(r'^get_artist/(?P<id>[0-9]+)/$', AjaxArtist.as_view(), name='ajax_artist'),
    url(r'^get_club/(?P<id>[0-9]+)/$', AjaxClub.as_view(), name='ajax_club'),

    url(r'^mailbox_ajax/$', MailboxAjax.as_view(), name='mailbox_ajax'),
    url(r'^message/$', MailBoxListView.as_view(), name='mailbox'),
    url(r'^message/out/$', MailBoxOutListView.as_view(), name='mailbox_out'),
    url(r'^message/(?P<pk>\d+)/$', MailboxDetailView.as_view(), name='mailbox_view'),

    url(r'^trade/$', TradeListView.as_view(), name='trade_list'),
    url(r'^trade/(?P<pk>\d+)/$', tradedetai, name='trade_view'),
    url(r'^trade/(?P<pk>\d+)/deals/$', DealsDetailView.as_view(), name='deals_view'),
    url(r'^trade/(?P<pk>\d+)/deals/print/$', DealsDetailViewPrint.as_view(), name='deals_print'),
    url(r'^trade/(?P<pk>\d+)/deals/pdf/$', DealsDetailViewPDF.as_view(), name='deals_pdf'),

    url(r'^send_mail/$', user_passes_test(lambda u: u.is_superuser or u.is_moderator)(SendMail.as_view()), name='send_mail'),

    url(r'^billing/$', TransactionCoinList.as_view(), name='billing'),
    url(r'^promo_code/$', PromoCodeFormView.as_view(), name='promo_code'),
    url(r'^paid_coin/$', PaidView.as_view(), name='paid_coin'),

    url(r'^$', login_required(MainView.as_view()), name='main'),
]

conf/urls.py
#-*- coding:utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from account.views import LogoutView, SigninFormView, ActivationView, IsActiveView, RePasswordFormView
from gigdate.views import Index, DateListView, LastListView
from seo.views import YandexMailVerifed, Robotstxt
from contents.views import LandingPage, LandingPage2

urlpatterns = [

    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<type_date>\w+)/$', Index.as_view(), name='home_month'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', Index.as_view(), name='home_month_dates'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<type_date>\w+)/$', DateListView.as_view(), name='date_day'),
    url(r'^last/$', LastListView.as_view(), name='last_all'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^user/', include('account.pub_urls', namespace='users')),
    url(r'^d/', include('gigdate.urls', namespace='gigdate')),
    url(r'^moder/', include('moderator.urls', namespace='moderator')),
    url(r'^info/', include('contents.urls', namespace='contents')),
    url(r'^crm/', include('crm.urls', namespace='crm')),

    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^signin/$', SigninFormView.as_view(), name='signin'),
    url(r'^is_active/$', IsActiveView.as_view(), name='is_active'),
    url(r'^is_active/resend/$', IsActiveView.as_view(), {'resend': 're_activate'}, name='re_is_active'),
    url(r'^user_activation/', ActivationView.as_view(), name='activation'),
    url(r'^repassword/', RePasswordFormView.as_view(), name='repassword'),
    url(r'^start/', LandingPage.as_view(), name='landingpage'),
    url(r'^start2/', LandingPage2.as_view(), name='landingpage2'),

    url(r'^cf6a2b36ecd97bf07de3f80906e7f2e9ab6cc852917cf7e7bd639612b615520c.html$', YandexMailVerifed.as_view()),
    url(r'^robots.txt', Robotstxt.as_view()),

    url(r'^$', Index.as_view(), name='home'),

    url(r'^(?P<type_date>\w+)/$', Index.as_view(), name='home_two'),
]


# Инициализируем папку media
if settings.DEBUG:
    if settings.MEDIA_ROOT:
        from django.conf.urls.static import static
        from django.contrib.staticfiles.urls import staticfiles_urlpatterns
        urlpatterns += static(settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)
    # Эта строка опциональна и будет добавлять url'ы только при DEBUG = True
    urlpatterns += staticfiles_urlpatterns()

crm/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.decorators import user_passes_test
from crm.views import HomeCRM, TicketListView, TicketDetailView, ChartUserStaticJS, UsersVenuesListView,\
    UsersVenuesDetailView


urlpatterns = [
    url(r'^$', user_passes_test(lambda u: u.is_superuser or u.is_moderator)(HomeCRM.as_view()), name='home'),
    url(r'^tickets/$', user_passes_test(lambda u: u.is_superuser or u.is_moderator)(TicketListView.as_view()),
        name='tickets'),
    url(r'^ticket/(?P<pk>\d+)/$',
        user_passes_test(lambda u: u.is_superuser or u.is_moderator)(TicketDetailView.as_view()), name='ticket_views'),
    url(r'^chart/user_static.js$', user_passes_test(lambda u: u.is_superuser or u.is_moderator)(ChartUserStaticJS.as_view()),
        name='chart_user_static'),

    url(r'^users/venues/$', user_passes_test(lambda u: u.is_superuser or u.is_moderator)(UsersVenuesListView.as_view()),
        name='users_venues'),
    url(r'^users/venues/(?P<pk>\d+)/$', user_passes_test(lambda u: u.is_superuser or u.is_moderator)(UsersVenuesDetailView.as_view()),
        name='users_venues_view'),
]

trade/urls.py
# -*- coding: utf-8 -*-

trade/models.py
#-*- coding:utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from tinymce.models import HTMLField
from django.core.urlresolvers import reverse
from account.models import User, ArtistProfile, ClubProfile
from common.models import MethodsAdvert
from gigdate.models import DateAll
from common.files import get_file_path


class Trades(models.Model):
    """
        Заявки
    """
    create          = models.DateTimeField(auto_now_add=True)
    update          = models.DateTimeField(auto_now=True)
    create_deal     = models.DateTimeField(_(u'#Сделка'), blank=True, null=True, editable=False, help_text=_(u"Дата создания сделки"))

    TYPEDATE0, TYPEDATE1, TYPEDATE2,  = range(0, 3)
    # Не менять порядок и формат написания. Используется в имени ПДФ файла, в моделе ContractText
    TYPE_DATES = (
        (TYPEDATE0, _(u'gigdate')),
        (TYPEDATE1, _(u'barter')),
        (TYPEDATE2, _(u'tender')),
    )
    date_all        = models.ForeignKey(DateAll, blank=False, null=True, related_name="trade_date")
    type_date       = models.IntegerField(_(u'#Тип даты'), default=TYPEDATE0, choices=TYPE_DATES, blank=True)

    user_date       = models.ForeignKey(User, blank=False, related_name="trade_user_date")
    user_trade      = models.ForeignKey(User, blank=False, related_name="trade_user_trade")
    artist_date     = models.ForeignKey(ArtistProfile, blank=True, null=True, related_name="trade_artist_date")
    artist_trade    = models.ForeignKey(ArtistProfile, blank=True, null=True, related_name="trade_artist_trade")
    club_date       = models.ForeignKey(ClubProfile, blank=True, null=True, related_name="trade_club_date")
    club_trade      = models.ForeignKey(ClubProfile, blank=True, null=True, related_name="trade_club_trade")

    view_date_user  = models.BooleanField(_(u'#Просмотр владельцем даты'), default=True)
    view_trade_user = models.BooleanField(_(u'#Просмотр создателем заявки'), default=False)

    # Статус бронирования
    trade_trade_user1 = models.BooleanField(_(u'#Покупатель заявка 1'), default=True)
    trade_trade_user2 = models.BooleanField(_(u'#Покупатель заявка 2'), default=False)
    trade_date_user = models.BooleanField(_(u'#Продавец заявка 1'), default=False)

    STRADE0, STRADE1, STRADE2, STRADE3, STRADE4 = range(0, 5)
    STATUS_TRADES = (
        (STRADE0, _(u'Expectation')),
        (STRADE1, _(u'Request')),
        (STRADE2, _(u'Deals')),
        (STRADE3, _(u'Finish')),
        (STRADE4, _(u'Rejected')),
    )
    # status_date    = models.IntegerField(_(u'#Статус продавца'), default=STRADE0, choices=STATUS_TRADES)
    status_trade   = models.IntegerField(_(u'#Статус'), default=STRADE1, choices=STATUS_TRADES)

    # тип и сумма гонорара
    EVENT0, EVENT1, EVENT2 = range(0, 3)
    EVENT_TYPE = (
        (EVENT0, _(u'Public')),
        (EVENT1, _(u'Private')),
        (EVENT2, _(u'Other')),
    )
    FEEEVENT0, FEEEVENT1, FEEEVENT2 = range(0, 3)
    FEE_EVENT_TYPE = (
        (EVENT0, _(u'Contractual fee')),
        (EVENT1, _(u'Fixed fee')),
        (EVENT2, _(u'Another fee')),
    )
    CONTRAC0, CONTRAC1, CONTRAC2 = range(0, 3)
    CONTRACTS = (
        (CONTRAC0, _(u'Artists contract')),
        # (CONTRAC1, _(u'Customers contract')),
        (CONTRAC2, _(u'Gigcenter contract form')),
    )

    CON0 = (CONTRAC0, _(u'Artists contract')),
    # CON1 = (CONTRAC1, _(u'Customers contract')),
    CON2 = (CONTRAC2, _(u'Gigcenter contract form')),
    event_type        = models.IntegerField(_(u'#Тип мероприятия'), choices=EVENT_TYPE, blank=True, null=True)
    fee_event_type    = models.IntegerField(_(u'#Тип гонорара'), default=FEEEVENT0, choices=FEE_EVENT_TYPE, blank=True, null=True)
    mony_fix          = models.PositiveIntegerField(_(u"#Сумма гонорара"), blank=True, null=True)
    mony_edit         = models.BooleanField(_(u'#Запрет изменять гонорар'), default=False)
    contracts         = models.IntegerField(_(u'#Форма Договора'), choices=CONTRACTS, blank=True, null=True)

    b_event_type      = models.IntegerField(_(u'#Тип мероприятия бартер'), choices=EVENT_TYPE, blank=True, null=True)
    b_fee_event_type  = models.IntegerField(_(u'#Тип гонорара бартер'), default=FEEEVENT0, choices=FEE_EVENT_TYPE, blank=True, null=True)
    b_mony_fix        = models.PositiveIntegerField(_(u"#Сумма гонорара бартер"), blank=True, null=True)
    b_mony_edit         = models.BooleanField(_(u'#Запрет изменять гонорар'), default=False)
    b_contracts       = models.IntegerField(_(u'#Договор бартера'), choices=CONTRACTS, blank=True, null=True)

    def __unicode__(self):
        return u"%s: %s" % (self.pk, self.date_all)

    def get_absolute_url(self):
        return reverse('account:trade_view', args=[self.pk])

    def get_absolute_url_deals(self):
        return reverse('account:deals_view', args=[self.pk])

    class Meta:
        verbose_name = _('Trade')
        verbose_name_plural = _('Trades')
        ordering = ['-update']


class Replys(Trades):
    """
        Ответы
    """
    EVENT0, EVENT1, EVENT2 = range(0, 3)
    EVENT_TYPE = (
        (EVENT0, _(u'Public')),
        (EVENT1, _(u'Private')),
        (EVENT2, _(u'Other')),
    )
    ACT0, ACT1, ACT2, ACT3 = range(0, 4)
    TYPE_ACTIONS = (
        (ACT0, _(u'Commercial')),
        (ACT1, _(u'Noncommercial')),
        (ACT2, _(u'Charitable')),
        (ACT3, _(u'Other'))
    )

    VE0, VE1 = range(0, 2)
    VENUES = (
        (VE0, _(u'Outdoor')),
        (VE1, _(u'Indoor'))
    )

    RENT0, RENT1, RENT2 = range(0, 3)
    RENTS = (
        (RENT0, _(u'Owned')),
        (RENT1, _(u'Long-term rent')),
        (RENT2, _(u'One-time rent'))
    )
    queries1        = models.CharField(_(u'#Название мероприятия'), max_length=255, null=True, blank=True)
    queries2        = models.IntegerField(_(u'#Тип мероприятия'), choices=EVENT_TYPE, blank=True, null=True)
    queries3        = models.IntegerField(_(u'#Характер мероприятия'), choices=TYPE_ACTIONS, blank=True, null=True)
    queries4        = models.IntegerField(_(u'#Закрытое или открытой место выступления'), choices=VENUES, blank=True, null=True)
    queries5        = models.CharField(_(u'#Размер сцены'), max_length=255, null=True, blank=True)
    queries6        = models.CharField(_(u'#Наличие спонсоров'), max_length=255, null=True, blank=True)
    queries7        = models.CharField(_(u'#Цена входного билета'), max_length=255, null=True, blank=True)
    queries8        = models.CharField(_(u'#Места распространения билетов'), max_length=255, null=True, blank=True)
    queries9        = models.CharField(_(u'#Время начала и конца'), max_length=255, null=True, blank=True)
    queries10       = models.CharField(_(u'#Время выступления артиста'), max_length=255, null=True, blank=True)
    queries11       = models.CharField(_(u'#Время саундчека'), max_length=255, null=True, blank=True)
    queries12       = models.CharField(_(u'#Лайнап мероприятия'), max_length=255, null=True, blank=True)
    queries13       = models.ManyToManyField(MethodsAdvert, verbose_name=_(u'#Методы рекламы'), blank=True)
    queries14       = models.CharField(_(u'#Наличие танцоров/go go/перформанс'), max_length=255, null=True, blank=True)
    queries15       = models.CharField(_(u'#Возраст аудитории'), max_length=255, null=True, blank=True)
    queries16       = models.CharField(_(u'#Тип аудитории'), max_length=255, null=True, blank=True)
    queries17       = models.IntegerField(_(u'#Аренда площадки'), choices=RENTS, blank=True, null=True)
    queries18       = models.TextField(_(u'#Артисты и агенты, с которыми заказчик уже работал'), null=True, blank=True)
    queries19       = models.TextField(_(u'#Артисты, которые подтверждены на выступление в ближайшем будущем на мероприятиях заказчика'), null=True, blank=True)
    queries20       = models.TextField(_(u'#Артисты, которые уже выступали на площадке проведения мероприятия'), null=True, blank=True)
    queries21       = models.TextField(_(u'#Артисты, которые подтверждены на выступление в ближайшем будущем на площадке проведения мероприятия'), null=True, blank=True)

    def __unicode__(self):
        return u"Ответы: %s" % self.pk

    class Meta:
        verbose_name = _(u'Reply')
        verbose_name_plural = _(u'Replys')


class ContractText(models.Model):
    """
    Текст договора
    """
    contract_type       = models.IntegerField(_(u'Type date'), default=Trades.TYPEDATE0, choices=Trades.TYPE_DATES)
    text_before         = HTMLField(_(u'Before'), null=True, blank=True)
    text_after          = HTMLField(_(u'After'), null=True, blank=True)

    def __unicode__(self):
        return u"%s" % self.get_contract_type_display()

    class Meta:
        verbose_name = _(u'Contract text')
        verbose_name_plural = _(u'Contract texts')
        unique_together = ('contract_type',)


class Chat(models.Model):
    """
        Чат в заявке
    """
    trands          = models.ForeignKey(Trades, verbose_name=_(u'#Заявка'), blank=True, null=True, related_name="trades_chat")
    create          = models.DateTimeField(_(u"#Создано"), auto_now_add=True)
    comment         = models.TextField(_(u'#Комментарий'), null=True, blank=True)
    files           = models.FileField(_(u'#Файл'), upload_to=get_file_path, blank=True, null=True)
    trades_author     = models.BooleanField(_(u'Владелец заявки'), default=True)

    def __unicode__(self):
        return "%s: %s" % (self.trands.pk, self.trades_author)

    class Meta:
        verbose_name = _(u'Chat')
        verbose_name_plural = _(u'Chats')

templates/trade/account/deals_view_barter.html
{% load static i18n filename user_tag %}
<h2>{% trans 'Deal`s number' %} <b>B{{ object.pk }}</b></h2>
{% if hidden_bottom %}<div class="right" style="bottom: 10px; position: relative;">
    <a href="{% url 'account:deals_print' object.pk %}" target="_blank"><img title="{% trans 'Send to print' %}" src="{% static 'images/print_icon.gif' %}" /></a>&nbsp;&nbsp;
    <a href="{% url 'account:deals_pdf' object.pk %}"><img title="{% trans 'To open in PDF' %}" src="{% static 'images/pdf_icon_black.png' %}" width="34" height="34" /></a>
</div>{% endif %}
<h3><strong>{% trans 'Date of the deal' %}</strong> {{ object.create_deal|date:"SHORT_DATE_FORMAT" }}</h3>
{% if contract_text and contract_text.text_before %}<div style="width: 95%">{{ contract_text.text_before|safe }}</div><br>{% endif %}

<div id="gigdatesadd">
    <div class="contract_text">

        {% trans 'This Deal for the mutual services of organizing a performance (hereinafter referred to as the Agreement)' %}
        "<a href="{{ object.artist_date.get_absolute_url }}">{{ object.artist_date.nickname }}</a>"
        {% trans '(hereinafter referred to as the Artist-1) and' %}
        "<a href="{{ object.artist_trade.get_absolute_url }}">{{ object.artist_trade.nickname }}</a>"
        {% trans '(hereinafter referred to as the Artist-2) is made between' %}
        "{{ object.user_date.get_full_name }}"
        {% trans 'from the name' %}

        {% if object.artist_date.agent %}"<a href="{{ object.artist_date.agent.get_absolute_url }}">{{ object.artist_date.agent.nickname }}</a>"{% else %}"<a href="{{ object.artist_date.get_absolute_url }}">{{ object.artist_date.nickname }}</a>"{% endif %}
        {% trans '(hereinafter referred to as the Agent-1) representing the Artist-1’s interests and' %}
        "{{ object.user_trade.get_full_name }}"
        {% trans 'from the name' %}

        {% if object.artist_trade.agent %}"<a href="{{ object.artist_trade.agent.get_absolute_url }}">{{ object.artist_trade.agent.nickname }}</a>"{% else %}"<a href="{{ object.artist_trade.get_absolute_url }}">{{ object.artist_trade.nickname }}</a>"{% endif %}
        {% trans '(hereinafter referred to as the Agent-2) representing the Artist-2’s interests.' %}

        <br><br>

        <h3><strong>{% trans 'Deal data - 1' %}</strong></h3>

        <b>{% trans 'Date of the performance' %}</b> {{ object.date_all.dates }}<br>
        <b>{% trans 'Venue' %}</b> {{ object.club_trade.nickname }}<br>
        <b>{% trans 'Venue address' %}</b> {{ object.club_trade.country }}, {{ object.club_trade.city }}, {{ object.club_trade.address }}<br>
        <b>{% trans 'Contract form' %} </b>{% if object.contracts == 2 %}<a href="/info/page/Gigcenter_agreement_form_3/">{{ object.get_contracts_display }}</a><br>
            <b>{% trans 'Fee payment schedule' %}</b> {{ object.date_all.get_payment_plan_display }}{% else %}{{ object.get_contracts_display }}{% endif %}<br>
        <b>{% trans 'Event type' %}</b> {{ object.get_event_type_display }}<br>
        <b>{% trans 'Fee' %}</b> {{ object.mony_fix }}<br>
        <b>{% trans 'Preferred currency of fee payment' %}</b> {{ object.date_all.get_currency_display }}<br>
        <b>{% trans 'Preferred form of fee payment' %}</b> {% for payment_method in object.date_all.payment_method.all %}{{ payment_method }}{% if not forloop.last %}, {% endif %}{% endfor %}<br>
        <b>{% trans 'Rider payments' %}</b> {{ object.date_all.get_rider_payments_display }} {% for rider in object.artist_date.rider.all %}<a href="{{ MEDIA_URL }}{{ rider.file }}">{% trans 'Rider' %} {{ forloop.counter }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}<br>
        <b>{% trans 'Transportation costs' %}</b> {{ object.date_all.get_transport_payments_display }}<br>
        <br>

        <h3><strong>{% trans 'Subject and terms according to Deal data - 1' %}</strong></h3>
        {% blocktrans %}
        The Agent-2 provides the Artist-1’s performance on the Venue on the Date of the performance,
        as well as it’s his responsibility to provide compliance with all the conditions of this Agreement.
        The Artist-1 is responsible for performing on the Venue on the Date of the performance.
        The Agent-2 is obliged to and guarantees organizing the Artist-1’s performance on the Venue on
        the Date of the performance and for the Fee, as well as compliance with all the conditions of this Agreement.<br><br>

        The Agreement comes into force the moment it is created and is valid until the parties have met all the
        commitments of the Agreement to the full extent.<br><br>

        The Date of the Artist-1’s performance is considered to be publicly taken the moment this Agreement is created.<br><br>

        The parties are subject to the Agreement form stated in the information box Contract form of the section
        Deal data-1.
        {% endblocktrans %}
        <br><br>
        <h3><strong>{% trans 'Deal data - 2' %}</strong></h3>

        <b>{% trans 'Response performance' %}</b> {{ object.date_all.get_sub_model.reply_speech }} {% trans 'months' %}<br>
        <b>{% trans 'Venue' %}</b> {{ object.club_date.nickname }}<br>
        <b>{% trans 'Venue address' %}</b> {{ object.club_date.country }}, {{ object.club_date.city }}, {{ object.club_date.address }}<br>
        <b>{% trans 'Contract form' %}</b> {% if object.b_contracts == 2 %}<a href="/info/page/Gigcenter_agreement_form_3/">{{ object.get_b_contracts_display }}</a><br>
            <b>{% trans 'Fee payment schedule' %}</b> {{ object.date_all.get_sub_model.get_payment_plan_display }}{% else %}{{ object.get_b_contracts_display }}{% endif %}<br>
        <b>{% trans 'Event type' %}</b> {{ object.get_b_event_type_display }}<br>
        <b>{% trans 'Fee' %}</b> {{ object.b_mony_fix }}<br>
        <b>{% trans 'Preferred currency of fee payment' %}</b> {{ object.date_all.get_sub_model.get_barter_currency_display }}<br>
        <b>{% trans 'Preferred form of fee payment' %}</b> {% for payment_method in object.date_all.get_sub_model.barter_payment_method.all %}{{ payment_method }}{% if not forloop.last %}, {% endif %}{% endfor %}<br>
        <b>{% trans 'Rider payments' %}</b> {{ object.date_all.get_sub_model.get_barter_rider_payments_display }} {% for rider in object.artist_trade.rider.all %}<a href="{{ MEDIA_URL }}{{ rider.file }}">{% trans 'Rider' %} {{ forloop.counter }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}<br>
        <b>{% trans 'Transportation costs' %}</b> {{ object.date_all.get_sub_model.get_barter_transport_payments_display }}<br>
        <br>

        <h3><strong>{% trans 'Subject and terms according to Deal data - 2' %}</strong></h3>
        {% blocktrans %}
         	The Agent-1 provides the Artist-2’s performance on the Venue on the selected date of the response
            performance period, as well as it’s his responsibility to provide compliance with all the conditions
            of this Agreement. The Artist-2 is responsible for performing on the Venue on the selected date of the
            response performance period. The Agent-1 is obliged to and guarantees organizing the Artist-2’s
            performance on the Venue on the selected date of the response performance period and for the Fee,
            as well as compliance with all the conditions of this Agreement.<br><br>

            The Agreement comes into force the moment it is created and is valid until the parties have met all
            the commitments of the Agreement to the full extent.<br><br>

            The selected date of the response performance period of the Artist-2’s performance is considered to
            be publicly taken the moment this date is chosen.<br><br>
            The parties are subject to the Agreement form stated in the information box Contract form of
            the section Deal data-2.<br>
        {% endblocktrans %}

        <br><br>
        {% if object.contracts == 2 %}
            {% if contract_text and contract_text.text_after %}<div style="width: 95%">{{ contract_text.text_after|safe }}</div><br>{% endif %}
        {% endif %}
    </div>

    <br><br>
    <div class="chat">
        {% if chat %}
            <h3><strong>{% trans 'Messages' %}</strong></h3>
            {% for ch in chat %}
        <div class="comments">
            {% if ch.trades_author %}
                <a href="{{ object.artist_trade.get_absolute_url }}"><strong{% if object.user_trade == request.user %} style="color: #00681C;" title="{% trans 'Me profile' %}"{% endif %}>{{ object.artist_trade.nickname }}</strong></a>
            {% else %}
                <a href="{{ object.artist_date.get_absolute_url }}"><strong{% if object.user_date == request.user %} style="color: #00681C;" title="{% trans 'Me profile' %}"{% endif %}>{{ object.artist_date.nickname }}</strong></a>
            {% endif %}
            <i>{{ ch.create }}</i><br>
            {% if ch.comment %}{{ ch.comment|linebreaksbr }}<br>{% endif %}
            {% if ch.files %}{% trans 'File:' %} <a href="{{ MEDIA_URL }}{{ ch.files }}" target="_blank">{{ ch.files|filename }}</a><br>{% endif %}
        </div><div class="line"></div>
            {% endfor %}
        {% endif %}
    </div>

</div>