conf/urls.py
#-*- coding:utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from account.views import LogoutView, SigninFormView, ActivationView, IsActiveView, RePasswordFormView
from gigdate.views import Index, DateListView, LastListView
from seo.views import YandexMailVerifed, Robotstxt
from contents.views import LandingPage, LandingPage2

urlpatterns = [

    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<type_date>\w+)/$', Index.as_view(), name='home_month'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', Index.as_view(), name='home_month_dates'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<type_date>\w+)/$', DateListView.as_view(), name='date_day'),
    url(r'^last/$', LastListView.as_view(), name='last_all'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^user/', include('account.pub_urls', namespace='users')),
    url(r'^d/', include('gigdate.urls', namespace='gigdate')),
    url(r'^moder/', include('moderator.urls', namespace='moderator')),
    url(r'^info/', include('contents.urls', namespace='contents')),
    url(r'^crm/', include('crm.urls', namespace='crm')),

    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^signin/$', SigninFormView.as_view(), name='signin'),
    url(r'^is_active/$', IsActiveView.as_view(), name='is_active'),
    url(r'^is_active/resend/$', IsActiveView.as_view(), {'resend': 're_activate'}, name='re_is_active'),
    url(r'^user_activation/', ActivationView.as_view(), name='activation'),
    url(r'^repassword/', RePasswordFormView.as_view(), name='repassword'),
    url(r'^start/', LandingPage.as_view(), name='landingpage'),
    url(r'^start2/', LandingPage2.as_view(), name='landingpage2'),

    url(r'^cf6a2b36ecd97bf07de3f80906e7f2e9ab6cc852917cf7e7bd639612b615520c.html$', YandexMailVerifed.as_view()),
    url(r'^robots.txt', Robotstxt.as_view()),

    url(r'^$', Index.as_view(), name='home'),

    url(r'^(?P<type_date>\w+)/$', Index.as_view(), name='home_two'),
]


# Инициализируем папку media
if settings.DEBUG:
    if settings.MEDIA_ROOT:
        from django.conf.urls.static import static
        from django.contrib.staticfiles.urls import staticfiles_urlpatterns
        urlpatterns += static(settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)
    # Эта строка опциональна и будет добавлять url'ы только при DEBUG = True
    urlpatterns += staticfiles_urlpatterns()

contents/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from contents.views import PageDetailView, FAQDetailView, FAQListView, NewsDetailView, NewsListView, AjaxFavorites,\
    AjaxBookmarks, FavoritesListView, FavoritesDeleteView, BookmarksListView, BookmarksDeleteView,\
    TicketFormView, FinalView, TestSendMail


urlpatterns = [
    url(r'^page/(?P<slug>\w+)_(?P<pk>\d+)/$', PageDetailView.as_view(), name='page'),
    url(r'^faq/(?P<pk>\d+)/$', FAQDetailView.as_view(), name='faq'),
    url(r'^faq/$', FAQListView.as_view(), name='faqs'),

    url(r'^news/$', NewsListView.as_view(), name='news'),
    url(r'^news/(?P<slug>\w+)_(?P<pk>\d+)/$', NewsDetailView.as_view(), name='news_index'),

    url(r'^add_favorites/(?P<user_id>[0-9]+)_(?P<type_data>\w+)/$', AjaxFavorites.as_view(), name='ajax_favorite'),
    url(r'^add_bookmarks/(?P<user_id>[0-9]+)_(?P<type_data>\w+)/$', AjaxBookmarks.as_view(), name='ajax_bookmark'),
    url(r'^favorite/$', FavoritesListView.as_view(), name='favorite_list'),
    url(r'^favorite/(?P<pk>\d+)/$', FavoritesDeleteView.as_view(), name='favorite_delete'),
    url(r'^bookmarks/$', BookmarksListView.as_view(), name='bookmark_list'),
    url(r'^bookmarks/(?P<pk>\d+)/$', BookmarksDeleteView.as_view(), name='bookmark_delete'),

    url(r'^support/$', TicketFormView.as_view(), name='support'),
    url(r'^support/final/$', FinalView.as_view(), name='support_final'),
    url(r'^test_send_email/$', TestSendMail.as_view(), name='test_send_email'),
]

crm/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.decorators import user_passes_test
from crm.views import HomeCRM, TicketListView, TicketDetailView, ChartUserStaticJS, UsersVenuesListView,\
    UsersVenuesDetailView


urlpatterns = [
    url(r'^$', user_passes_test(lambda u: u.is_superuser or u.is_moderator)(HomeCRM.as_view()), name='home'),
    url(r'^tickets/$', user_passes_test(lambda u: u.is_superuser or u.is_moderator)(TicketListView.as_view()),
        name='tickets'),
    url(r'^ticket/(?P<pk>\d+)/$',
        user_passes_test(lambda u: u.is_superuser or u.is_moderator)(TicketDetailView.as_view()), name='ticket_views'),
    url(r'^chart/user_static.js$', user_passes_test(lambda u: u.is_superuser or u.is_moderator)(ChartUserStaticJS.as_view()),
        name='chart_user_static'),

    url(r'^users/venues/$', user_passes_test(lambda u: u.is_superuser or u.is_moderator)(UsersVenuesListView.as_view()),
        name='users_venues'),
    url(r'^users/venues/(?P<pk>\d+)/$', user_passes_test(lambda u: u.is_superuser or u.is_moderator)(UsersVenuesDetailView.as_view()),
        name='users_venues_view'),
]

trade/models.py
#-*- coding:utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from tinymce.models import HTMLField
from django.core.urlresolvers import reverse
from account.models import User, ArtistProfile, ClubProfile
from common.models import MethodsAdvert
from gigdate.models import DateAll
from common.files import get_file_path


class Trades(models.Model):
    """
        Заявки
    """
    create          = models.DateTimeField(auto_now_add=True)
    update          = models.DateTimeField(auto_now=True)
    create_deal     = models.DateTimeField(_(u'#Сделка'), blank=True, null=True, editable=False, help_text=_(u"Дата создания сделки"))

    TYPEDATE0, TYPEDATE1, TYPEDATE2,  = range(0, 3)
    # Не менять порядок и формат написания. Используется в имени ПДФ файла, в моделе ContractText
    TYPE_DATES = (
        (TYPEDATE0, _(u'gigdate')),
        (TYPEDATE1, _(u'barter')),
        (TYPEDATE2, _(u'tender')),
    )
    date_all        = models.ForeignKey(DateAll, blank=False, null=True, related_name="trade_date")
    type_date       = models.IntegerField(_(u'#Тип даты'), default=TYPEDATE0, choices=TYPE_DATES, blank=True)

    user_date       = models.ForeignKey(User, blank=False, related_name="trade_user_date")
    user_trade      = models.ForeignKey(User, blank=False, related_name="trade_user_trade")
    artist_date     = models.ForeignKey(ArtistProfile, blank=True, null=True, related_name="trade_artist_date")
    artist_trade    = models.ForeignKey(ArtistProfile, blank=True, null=True, related_name="trade_artist_trade")
    club_date       = models.ForeignKey(ClubProfile, blank=True, null=True, related_name="trade_club_date")
    club_trade      = models.ForeignKey(ClubProfile, blank=True, null=True, related_name="trade_club_trade")

    view_date_user  = models.BooleanField(_(u'#Просмотр владельцем даты'), default=True)
    view_trade_user = models.BooleanField(_(u'#Просмотр создателем заявки'), default=False)

    # Статус бронирования
    trade_trade_user1 = models.BooleanField(_(u'#Покупатель заявка 1'), default=True)
    trade_trade_user2 = models.BooleanField(_(u'#Покупатель заявка 2'), default=False)
    trade_date_user = models.BooleanField(_(u'#Продавец заявка 1'), default=False)

    STRADE0, STRADE1, STRADE2, STRADE3, STRADE4 = range(0, 5)
    STATUS_TRADES = (
        (STRADE0, _(u'Expectation')),
        (STRADE1, _(u'Request')),
        (STRADE2, _(u'Deals')),
        (STRADE3, _(u'Finish')),
        (STRADE4, _(u'Rejected')),
    )
    # status_date    = models.IntegerField(_(u'#Статус продавца'), default=STRADE0, choices=STATUS_TRADES)
    status_trade   = models.IntegerField(_(u'#Статус'), default=STRADE1, choices=STATUS_TRADES)

    # тип и сумма гонорара
    EVENT0, EVENT1, EVENT2 = range(0, 3)
    EVENT_TYPE = (
        (EVENT0, _(u'Public')),
        (EVENT1, _(u'Private')),
        (EVENT2, _(u'Other')),
    )
    FEEEVENT0, FEEEVENT1, FEEEVENT2 = range(0, 3)
    FEE_EVENT_TYPE = (
        (EVENT0, _(u'Contractual fee')),
        (EVENT1, _(u'Fixed fee')),
        (EVENT2, _(u'Another fee')),
    )
    CONTRAC0, CONTRAC1, CONTRAC2 = range(0, 3)
    CONTRACTS = (
        (CONTRAC0, _(u'Artists contract')),
        # (CONTRAC1, _(u'Customers contract')),
        (CONTRAC2, _(u'Gigcenter contract form')),
    )

    CON0 = (CONTRAC0, _(u'Artists contract')),
    # CON1 = (CONTRAC1, _(u'Customers contract')),
    CON2 = (CONTRAC2, _(u'Gigcenter contract form')),
    event_type        = models.IntegerField(_(u'#Тип мероприятия'), choices=EVENT_TYPE, blank=True, null=True)
    fee_event_type    = models.IntegerField(_(u'#Тип гонорара'), default=FEEEVENT0, choices=FEE_EVENT_TYPE, blank=True, null=True)
    mony_fix          = models.PositiveIntegerField(_(u"#Сумма гонорара"), blank=True, null=True)
    mony_edit         = models.BooleanField(_(u'#Запрет изменять гонорар'), default=False)
    contracts         = models.IntegerField(_(u'#Форма Договора'), choices=CONTRACTS, blank=True, null=True)

    b_event_type      = models.IntegerField(_(u'#Тип мероприятия бартер'), choices=EVENT_TYPE, blank=True, null=True)
    b_fee_event_type  = models.IntegerField(_(u'#Тип гонорара бартер'), default=FEEEVENT0, choices=FEE_EVENT_TYPE, blank=True, null=True)
    b_mony_fix        = models.PositiveIntegerField(_(u"#Сумма гонорара бартер"), blank=True, null=True)
    b_mony_edit         = models.BooleanField(_(u'#Запрет изменять гонорар'), default=False)
    b_contracts       = models.IntegerField(_(u'#Договор бартера'), choices=CONTRACTS, blank=True, null=True)

    def __unicode__(self):
        return u"%s: %s" % (self.pk, self.date_all)

    def get_absolute_url(self):
        return reverse('account:trade_view', args=[self.pk])

    def get_absolute_url_deals(self):
        return reverse('account:deals_view', args=[self.pk])

    class Meta:
        verbose_name = _('Trade')
        verbose_name_plural = _('Trades')
        ordering = ['-update']


class Replys(Trades):
    """
        Ответы
    """
    EVENT0, EVENT1, EVENT2 = range(0, 3)
    EVENT_TYPE = (
        (EVENT0, _(u'Public')),
        (EVENT1, _(u'Private')),
        (EVENT2, _(u'Other')),
    )
    ACT0, ACT1, ACT2, ACT3 = range(0, 4)
    TYPE_ACTIONS = (
        (ACT0, _(u'Commercial')),
        (ACT1, _(u'Noncommercial')),
        (ACT2, _(u'Charitable')),
        (ACT3, _(u'Other'))
    )

    VE0, VE1 = range(0, 2)
    VENUES = (
        (VE0, _(u'Outdoor')),
        (VE1, _(u'Indoor'))
    )

    RENT0, RENT1, RENT2 = range(0, 3)
    RENTS = (
        (RENT0, _(u'Owned')),
        (RENT1, _(u'Long-term rent')),
        (RENT2, _(u'One-time rent'))
    )
    queries1        = models.CharField(_(u'#Название мероприятия'), max_length=255, null=True, blank=True)
    queries2        = models.IntegerField(_(u'#Тип мероприятия'), choices=EVENT_TYPE, blank=True, null=True)
    queries3        = models.IntegerField(_(u'#Характер мероприятия'), choices=TYPE_ACTIONS, blank=True, null=True)
    queries4        = models.IntegerField(_(u'#Закрытое или открытой место выступления'), choices=VENUES, blank=True, null=True)
    queries5        = models.CharField(_(u'#Размер сцены'), max_length=255, null=True, blank=True)
    queries6        = models.CharField(_(u'#Наличие спонсоров'), max_length=255, null=True, blank=True)
    queries7        = models.CharField(_(u'#Цена входного билета'), max_length=255, null=True, blank=True)
    queries8        = models.CharField(_(u'#Места распространения билетов'), max_length=255, null=True, blank=True)
    queries9        = models.CharField(_(u'#Время начала и конца'), max_length=255, null=True, blank=True)
    queries10       = models.CharField(_(u'#Время выступления артиста'), max_length=255, null=True, blank=True)
    queries11       = models.CharField(_(u'#Время саундчека'), max_length=255, null=True, blank=True)
    queries12       = models.CharField(_(u'#Лайнап мероприятия'), max_length=255, null=True, blank=True)
    queries13       = models.ManyToManyField(MethodsAdvert, verbose_name=_(u'#Методы рекламы'), blank=True)
    queries14       = models.CharField(_(u'#Наличие танцоров/go go/перформанс'), max_length=255, null=True, blank=True)
    queries15       = models.CharField(_(u'#Возраст аудитории'), max_length=255, null=True, blank=True)
    queries16       = models.CharField(_(u'#Тип аудитории'), max_length=255, null=True, blank=True)
    queries17       = models.IntegerField(_(u'#Аренда площадки'), choices=RENTS, blank=True, null=True)
    queries18       = models.TextField(_(u'#Артисты и агенты, с которыми заказчик уже работал'), null=True, blank=True)
    queries19       = models.TextField(_(u'#Артисты, которые подтверждены на выступление в ближайшем будущем на мероприятиях заказчика'), null=True, blank=True)
    queries20       = models.TextField(_(u'#Артисты, которые уже выступали на площадке проведения мероприятия'), null=True, blank=True)
    queries21       = models.TextField(_(u'#Артисты, которые подтверждены на выступление в ближайшем будущем на площадке проведения мероприятия'), null=True, blank=True)

    def __unicode__(self):
        return u"Ответы: %s" % self.pk

    class Meta:
        verbose_name = _(u'Reply')
        verbose_name_plural = _(u'Replys')


class ContractText(models.Model):
    """
    Текст договора
    """
    contract_type       = models.IntegerField(_(u'Type date'), default=Trades.TYPEDATE0, choices=Trades.TYPE_DATES)
    text_before         = HTMLField(_(u'Before'), null=True, blank=True)
    text_after          = HTMLField(_(u'After'), null=True, blank=True)

    def __unicode__(self):
        return u"%s" % self.get_contract_type_display()

    class Meta:
        verbose_name = _(u'Contract text')
        verbose_name_plural = _(u'Contract texts')
        unique_together = ('contract_type',)


class Chat(models.Model):
    """
        Чат в заявке
    """
    trands          = models.ForeignKey(Trades, verbose_name=_(u'#Заявка'), blank=True, null=True, related_name="trades_chat")
    create          = models.DateTimeField(_(u"#Создано"), auto_now_add=True)
    comment         = models.TextField(_(u'#Комментарий'), null=True, blank=True)
    files           = models.FileField(_(u'#Файл'), upload_to=get_file_path, blank=True, null=True)
    trades_author     = models.BooleanField(_(u'Владелец заявки'), default=True)

    def __unicode__(self):
        return "%s: %s" % (self.trands.pk, self.trades_author)

    class Meta:
        verbose_name = _(u'Chat')
        verbose_name_plural = _(u'Chats')

contents/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _


class TestSendMailForm(forms.Form):
    email_from = forms.ChoiceField(choices=(
        (settings.EMAIL_TICKETS, settings.EMAIL_TICKETS),
        (False, settings.DEFAULT_FROM_EMAIL)
    ), required=False,)
    email_to = forms.EmailField()
    subject = forms.CharField(initial='default subject')
    message = forms.CharField(initial='default text')
    raise_error = forms.BooleanField(required=False)

templates/contents/bookmarks_confirm_delete.html
{% extends 'base.html' %}
{% load static i18n  %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>{% trans 'Are you sure you want to delete bookmarks' %} "{{ object.date_all.dates }} {% trans 'from' %} {{ object.date_all.username_child }}"?</p>
    <input type="submit" value="{% trans 'Confirm' %}" />
</form>
{% endblock %}

templates/contents/bookmarks_list.html
{% extends 'base.html' %}
{% load staticfiles i18n %}

{% block content %}
    <div class="blue-line" style="margin-bottom:30px;"></div>
    <div class="main-wrapper">
        <div class="content nowidth">
            <div class="table-filter">
                <div class="total">{% trans 'All bookmarks' %} <span class="red">{{ page_obj.paginator.count }}</span></div>
            </div>
            <table class="table">
                {% for d in object_list %}
                    <tr {% cycle 'class="even"' '' %}>
                        <td style="width: 50px;">
                            <span class="date">{{ d.date_all.dates|date:"d" }}<br/>{{ d.date_all.dates|date:"F" }}{% if d.date_all.second_country %}<br><img src="{% static 'images/ui_2Date.png' %}" />{% endif %}</span>
                        </td>
                        <td>
                            <div class="min-info">
                                <div class="visual"><img src="{% if d.date_all.username_child.avatar %}{{ MEDIA_URL }}{{ d.date_all.username_child.avatar }}{% else %}{% static 'images/bg-ava.gif' %}{% endif %}" width="58" height="58" alt=""/></div>
                                <div class="holder">
                                    <div class="name"><a href="{% if tp == 'barters' %}{{ d.date_all.username_child.get_absolute_url }}{% else %}{{ d.date_all.username_child.get_absolute_url }}{% endif %}">{{ d.date_all.username_child }}</a></div>
                                    <ul class="list">
                                        <li>{% if d.country.width != '0' or d.country.height != '0' %}<div class="flag_country" style="background-position: -{{ d.date_all.username_child.country.width }}px -{{ d.date_all.username_child.country.height }}px"></div>{% endif %}{{ d.date_all.username_child.country.title }}, {{ d.date_all.username_child.city.title }}</li>
                                        <li>{% for pf in d.date_all.username_child.genre.all %}{{ pf.title }}{% if not forloop.last %}, {% endif %}{% endfor %}</li>
                                    </ul>
                                </div>
                            </div>
                        </td>
                        <td class="last" style="width: 150px;">
                            <div class="bottom-wrap">
{#                                <span class="premium"></span>#}
                                <a class="red-btn" href="{{ d.date_all.get_absolute_url_view }}">
                                    <span>{% trans 'Book' %} {{ d.date_all.get_type_date_display|lower }}</span>
                                </a>
                            </div>
                        </td>
                        <td><a href="{% url 'contents:bookmark_delete' d.pk %}">x</a></td>
                    </tr>
                {% empty %}
                    <tr><td style="text-align: center">{% trans 'Dates not found' %}</td></tr>
                {% endfor %}
            </table>
            {% if is_paginated %}<div class="pagination pagination-centered">
                <ul>
                    {% if page_obj.has_previous %}<li {% if not page_obj.has_previous %}class="disabled"{% endif %}><a href="{% if page_obj.previous_page_number == 1 %}./{% else %}?page={{ page_obj.previous_page_number }}{% endif %}"><</a></li>{% endif %}

                    {% for p in page_obj.paginator.page_range %}
                        <li {% ifequal p page_obj.number %}class="active"{% endifequal %}><a href="{% if p == 1 %}./{% else %}?page={{ p }}{% endif %}">{{ p }}</a></li>
                    {% endfor %}

                    {% if page_obj.has_next %}<li {% if not page_obj.has_next %}class="disabled"{% endif %}><a href="?page={{ page_obj.next_page_number }}">></a></li>{% endif %}
                </ul>
            </div>{% endif %}

        </div>

    </div>
    <div class="blue-line"></div>
{% endblock %}

templates/contents/faq.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
    <div class="blue-line" style="margin-bottom:30px;"></div>
    <div class="main-wrapper">
        <div class="content">
            {% block section_content %}
                <h1>{{ page.name }}</h1>
                <div class="gray-line" style="margin-bottom:15px;"></div>
                <div class="article">
                   {{ page.text|safe }}
                </div>
            {% endblock %}
        </div>
        <div class="sidebar">
            {% block sidebar %}

            {% endblock %}
        </div>
    </div>
{% endblock %}

templates/contents/faqcategory_list.html
{% extends 'base.html' %}

{% load staticfiles i18n %}

{% block content %}
    <div class="blue-line" style="margin-bottom:30px;"></div>
    <div class="main-wrapper">
        <div class="content">
            <ol class="faq_list">
                {% for faq in object_list %}{% if faq.faq_category.all %}<li><h2>{{ faq.title }}</h2>
                    <ul class="faq_link">{% for rqst in faq.faq_category.all %}<li><a href="{{ rqst.get_absolute_url }}">{{ forloop.counter }}. {{ rqst.name }}</a></li>{% endfor %}</ul>
                </li>{% endif %}{% endfor %}
            </ol>
        </div>
        <div class="sidebar">
            {% block sidebar %}

            {% endblock %}
        </div>
    </div>
{% endblock %}

templates/contents/faqs.html
{% extends 'base.html' %}

{% load staticfiles i18n %}

{% block content %}
    <div class="blue-line" style="margin-bottom:30px;"></div>
    <div class="main-wrapper">
        <div class="content">
            {% block section_content %}
                {% for faq in items %}
                <h1>{{ faq.name }}</h1>
                <div class="article">
                   {{ faq.min_text|safe }}
                <br><a href="{{ faq.get_absolute_url }}">{% trans 'Read more...' %}</a>
                </div>

                <div class="gray-line" style="margin-bottom:15px;"></div>
                {% endfor %}
            {% endblock %}
        </div>
        <div class="sidebar">
            {% block sidebar %}

            {% endblock %}
        </div>
    </div>
{% endblock %}

templates/contents/favorites_confirm_delete.html
{% extends 'base.html' %}
{% load static i18n  %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>{% trans 'Are you sure you want to delete favorites' %} "{{ object.get_profile }}"?</p>
    <input type="submit" value="{% trans 'Confirm' %}" />
</form>
{% endblock %}

templates/contents/favorites_list.html
{% extends 'base.html' %}
{% load static i18n  %}

{% block content %}
<div class="list_users">
    <div id="left">
        <div class="head">
            <div class="bottom">
                <h3>{% trans 'Total Favorites' %}: {% if page_obj.paginator.count %}{{ page_obj.paginator.count }}{% else %}0{% endif %}</h3>
            </div>
            <div class="clear"></div>
        </div>
        <div class="content">
            <table>
            {% for user in object_list %}
                <tr>
                    <td style="width: 20px;">{% if user.get_profile.country.width != '0' or user.get_profile.country.height != '0' %}<div class="flag_country" style="background-position: -{{ user.get_profile.country.width }}px -{{ user.get_profile.country.height }}px;" title="{{ user.get_profile.country.title }}"></div>{% endif %}</td>
                    <td><div class="nickname"><a href="{{ user.get_profile.get_absolute_url }}">{{ user.get_profile }}</a></div></td>
                    <td><div class="nickname"></div></td>
                    <td><div class="genre">
                        <b>{{ user.get_type_data_display }}</b>
                        {% if user.agent and user.agent.type_agent.all %}<b> type:</b> {% for type_agent in user.agent.type_agent.all %}{{ type_agent }}{% if not forloop.last %}, {% endif %}{% endfor %}{% endif %}
                        {% if user.get_profile.genre.all %}<b> genre:</b> {% for genre in user.get_profile.genre.all %}{{ genre.title }}{% if not forloop.last %}, {% endif %}{% endfor %}{% endif %}
                    </div></td>
                    <td style="width: 20px;"><a href="{% url 'contents:favorite_delete' user.pk %}">x</a></td>
                </tr>
            {% empty %}
                <tr><td style="text-align: center">{% trans 'Favorites not found' %}</td></tr>
            {% endfor %}
            </table>

            {% if is_paginated %}<div class="pagination pagination-centered">
                <ul>
                    {% if page_obj.has_previous %}<li {% if not page_obj.has_previous %}class="disabled"{% endif %}><a href="{% if page_obj.previous_page_number == 1 %}./{% else %}?page={{ page_obj.previous_page_number }}{% endif %}"><</a></li>{% endif %}

                    {% for p in page_obj.paginator.page_range %}
                        <li {% ifequal p page_obj.number %}class="active"{% endifequal %}><a href="{% if p == 1 %}./{% else %}?page={{ p }}{% endif %}">{{ p }}</a></li>
                    {% endfor %}

                    {% if page_obj.has_next %}<li {% if not page_obj.has_next %}class="disabled"{% endif %}><a href="?page={{ page_obj.next_page_number }}">></a></li>{% endif %}
                </ul>
            </div>{% endif %}
        </div>
    </div>
    <div id="right"><!--right--></div>
</div>
{% endblock %}

templates/contents/news_detail.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
    <div class="blue-line" style="margin-bottom:30px;"></div>
    <div class="main-wrapper">
        <div class="content">
            {% block section_content %}
                <h1>{{ object.name }}</h1>
                <div class="gray-line" style="margin-bottom:15px;"></div>
                <div class="article">
                {% if object.images %}<img src="{{ MEDIA_URL }}{{ object.images }}" title="{{ object.name }}" alt="{{ object.name }}" style="float: left; margin: 0 12px 5px 0;" />{% endif %}
                   {{ object.text|safe }}
                </div>
            {% endblock %}
        </div>
        <div class="sidebar">
            {% block sidebar %}

            {% endblock %}
        </div>
    </div>
{% endblock %}

templates/contents/page.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
    <div class="blue-line" style="margin-bottom:30px;"></div>
    <div class="main-wrapper">
        <div class="content">
            {% block section_content %}
                <h1>{{ page.name }}</h1>
                <div class="gray-line" style="margin-bottom:15px;"></div>
                <div class="article">
                {% if page.images %}<img src="{{ MEDIA_URL }}{{ page.images }}" title="{{ page.name }}" alt="{{ page.name }}" style="float: left; margin: 0 12px 5px 0;" />{% endif %}
                   {{ page.text|safe }}
                </div>
            {% endblock %}
        </div>
        <div class="sidebar">
            {% block sidebar %}

            {% endblock %}
        </div>
    </div>
{% endblock %}